// Code generated by MockGen. DO NOT EDIT.
// Source: capture.go
//
// Generated by this command:
//
//	mockgen -source=capture.go -destination=mocks/mock_capturer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCapturer is a mock of Capturer interface.
type MockCapturer struct {
	ctrl     *gomock.Controller
	recorder *MockCapturerMockRecorder
	isgomock struct{}
}

// MockCapturerMockRecorder is the mock recorder for MockCapturer.
type MockCapturerMockRecorder struct {
	mock *MockCapturer
}

// NewMockCapturer creates a new mock instance.
func NewMockCapturer(ctrl *gomock.Controller) *MockCapturer {
	mock := &MockCapturer{ctrl: ctrl}
	mock.recorder = &MockCapturerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapturer) EXPECT() *MockCapturerMockRecorder {
	return m.recorder
}

// Capture mocks base method.
func (m *MockCapturer) Capture(ctx context.Context, scriptPath string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", ctx, scriptPath)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockCapturerMockRecorder) Capture(ctx, scriptPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockCapturer)(nil).Capture), ctx, scriptPath)
}
