// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexander-fenster/decloud/internal/deploy (interfaces: Lifecycle)
//
// Generated by this command:
//
//	mockgen -destination=../cli/mocks/mock_lifecycle.go -package=mocks github.com/alexander-fenster/decloud/internal/deploy Lifecycle
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	deploy "github.com/alexander-fenster/decloud/internal/deploy"
	gomock "go.uber.org/mock/gomock"
)

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// CaddyReload mocks base method.
func (m *MockLifecycle) CaddyReload(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaddyReload", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CaddyReload indicates an expected call of CaddyReload.
func (mr *MockLifecycleMockRecorder) CaddyReload(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaddyReload", reflect.TypeOf((*MockLifecycle)(nil).CaddyReload), ctx)
}

// Logs mocks base method.
func (m *MockLifecycle) Logs(ctx context.Context, name string, opts deploy.LogOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logs indicates an expected call of Logs.
func (mr *MockLifecycleMockRecorder) Logs(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockLifecycle)(nil).Logs), ctx, name, opts)
}

// Restart mocks base method.
func (m *MockLifecycle) Restart(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockLifecycleMockRecorder) Restart(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockLifecycle)(nil).Restart), ctx, name)
}

// Start mocks base method.
func (m *MockLifecycle) Start(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockLifecycleMockRecorder) Start(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLifecycle)(nil).Start), ctx, name)
}

// Status mocks base method.
func (m *MockLifecycle) Status(ctx context.Context, name string) (deploy.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, name)
	ret0, _ := ret[0].(deploy.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockLifecycleMockRecorder) Status(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockLifecycle)(nil).Status), ctx, name)
}

// Stop mocks base method.
func (m *MockLifecycle) Stop(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockLifecycleMockRecorder) Stop(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockLifecycle)(nil).Stop), ctx, name)
}

// Unregister mocks base method.
func (m *MockLifecycle) Unregister(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockLifecycleMockRecorder) Unregister(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockLifecycle)(nil).Unregister), ctx, name)
}
