// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexander-fenster/decloud/internal/deploy (interfaces: ServiceDeployer)
//
// Generated by this command:
//
//	mockgen -destination=../cli/mocks/mock_deployer.go -package=mocks github.com/alexander-fenster/decloud/internal/deploy ServiceDeployer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	deploy "github.com/alexander-fenster/decloud/internal/deploy"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceDeployer is a mock of ServiceDeployer interface.
type MockServiceDeployer struct {
	ctrl     *gomock.Controller
	recorder *MockServiceDeployerMockRecorder
	isgomock struct{}
}

// MockServiceDeployerMockRecorder is the mock recorder for MockServiceDeployer.
type MockServiceDeployerMockRecorder struct {
	mock *MockServiceDeployer
}

// NewMockServiceDeployer creates a new mock instance.
func NewMockServiceDeployer(ctrl *gomock.Controller) *MockServiceDeployer {
	mock := &MockServiceDeployer{ctrl: ctrl}
	mock.recorder = &MockServiceDeployerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceDeployer) EXPECT() *MockServiceDeployerMockRecorder {
	return m.recorder
}

// Deploy mocks base method.
func (m *MockServiceDeployer) Deploy(ctx context.Context, req deploy.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockServiceDeployerMockRecorder) Deploy(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockServiceDeployer)(nil).Deploy), ctx, req)
}
