package caddy

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/alexander-fenster/decloud/internal/registry"
)

//go:generate mockgen -source=generator.go -destination=mocks/mock_generator.go -package=mocks

// GeneratorInput is one row in the rendered Caddyfile.
type GeneratorInput struct {
	ServiceName   string
	ContainerName string
	Port          int
	Hostnames     []string
}

// Generator renders a Caddyfile from a slice of registered services.
type Generator interface {
	Generate(outPath string, services []*registry.Service) error
}

// NewGenerator returns the production generator.
func NewGenerator() Generator {
	return &textGenerator{}
}

type textGenerator struct{}

func (g *textGenerator) Generate(outPath string, services []*registry.Service) error {
	inputs := normalize(services)
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Caddyfile generated by decloud — do not edit by hand.")
	fmt.Fprintln(&buf, "# Re-run `decloud caddy reload` to refresh.")
	for _, in := range inputs {
		fmt.Fprintln(&buf)
		for _, host := range in.Hostnames {
			fmt.Fprintf(&buf, "%s {\n", host)
			fmt.Fprintf(&buf, "    reverse_proxy %s:%d\n", in.ContainerName, in.Port)
			fmt.Fprintln(&buf, "}")
		}
	}
	return writeFileAtomic(outPath, buf.Bytes())
}

func normalize(services []*registry.Service) []GeneratorInput {
	out := make([]GeneratorInput, 0, len(services))
	for _, svc := range services {
		hosts := make([]string, 0, len(svc.Config.Routes))
		for _, r := range svc.Config.Routes {
			if r.Hostname == "" {
				continue
			}
			hosts = append(hosts, r.Hostname)
		}
		if len(hosts) == 0 {
			continue
		}
		sort.Strings(hosts)
		container := svc.Config.State.ContainerName
		if container == "" {
			container = "decloud-" + svc.Config.Name
		}
		out = append(out, GeneratorInput{
			ServiceName:   svc.Config.Name,
			ContainerName: container,
			Port:          svc.Config.Run.Port,
			Hostnames:     hosts,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ServiceName < out[j].ServiceName })
	return out
}

func writeFileAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".caddyfile-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return err
	}
	if err := os.Chmod(tmpPath, 0o644); err != nil {
		os.Remove(tmpPath)
		return err
	}
	return os.Rename(tmpPath, path)
}
