// Code generated by MockGen. DO NOT EDIT.
// Source: reloader.go
//
// Generated by this command:
//
//	mockgen -source=reloader.go -destination=mocks/mock_reloader.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReloader is a mock of Reloader interface.
type MockReloader struct {
	ctrl     *gomock.Controller
	recorder *MockReloaderMockRecorder
	isgomock struct{}
}

// MockReloaderMockRecorder is the mock recorder for MockReloader.
type MockReloaderMockRecorder struct {
	mock *MockReloader
}

// NewMockReloader creates a new mock instance.
func NewMockReloader(ctrl *gomock.Controller) *MockReloader {
	mock := &MockReloader{ctrl: ctrl}
	mock.recorder = &MockReloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReloader) EXPECT() *MockReloaderMockRecorder {
	return m.recorder
}

// Reload mocks base method.
func (m *MockReloader) Reload(ctx context.Context, configPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload", ctx, configPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockReloaderMockRecorder) Reload(ctx, configPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockReloader)(nil).Reload), ctx, configPath)
}

// Validate mocks base method.
func (m *MockReloader) Validate(ctx context.Context, configPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, configPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockReloaderMockRecorder) Validate(ctx, configPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockReloader)(nil).Validate), ctx, configPath)
}
