// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go
//
// Generated by this command:
//
//	mockgen -source=driver.go -destination=mocks/mock_driver.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dockerdrv "github.com/alexander-fenster/decloud/internal/dockerdrv"
	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockDriver) Build(ctx context.Context, req dockerdrv.BuildRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockDriverMockRecorder) Build(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockDriver)(nil).Build), ctx, req)
}

// ContainerIP mocks base method.
func (m *MockDriver) ContainerIP(ctx context.Context, containerName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerIP", ctx, containerName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerIP indicates an expected call of ContainerIP.
func (mr *MockDriverMockRecorder) ContainerIP(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerIP", reflect.TypeOf((*MockDriver)(nil).ContainerIP), ctx, containerName)
}

// Exec mocks base method.
func (m *MockDriver) Exec(ctx context.Context, opts dockerdrv.ExecOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockDriverMockRecorder) Exec(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDriver)(nil).Exec), ctx, opts)
}

// ImagePull mocks base method.
func (m *MockDriver) ImagePull(ctx context.Context, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePull", ctx, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImagePull indicates an expected call of ImagePull.
func (mr *MockDriverMockRecorder) ImagePull(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePull", reflect.TypeOf((*MockDriver)(nil).ImagePull), ctx, ref)
}

// Inspect mocks base method.
func (m *MockDriver) Inspect(ctx context.Context, containerName string) (dockerdrv.InspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", ctx, containerName)
	ret0, _ := ret[0].(dockerdrv.InspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockDriverMockRecorder) Inspect(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockDriver)(nil).Inspect), ctx, containerName)
}

// Logs mocks base method.
func (m *MockDriver) Logs(ctx context.Context, containerName string, opts dockerdrv.LogsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, containerName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logs indicates an expected call of Logs.
func (mr *MockDriverMockRecorder) Logs(ctx, containerName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockDriver)(nil).Logs), ctx, containerName, opts)
}

// NetworkEnsure mocks base method.
func (m *MockDriver) NetworkEnsure(ctx context.Context, networkName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkEnsure", ctx, networkName)
	ret0, _ := ret[0].(error)
	return ret0
}

// NetworkEnsure indicates an expected call of NetworkEnsure.
func (mr *MockDriverMockRecorder) NetworkEnsure(ctx, networkName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkEnsure", reflect.TypeOf((*MockDriver)(nil).NetworkEnsure), ctx, networkName)
}

// Remove mocks base method.
func (m *MockDriver) Remove(ctx context.Context, containerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, containerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockDriverMockRecorder) Remove(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockDriver)(nil).Remove), ctx, containerName)
}

// Run mocks base method.
func (m *MockDriver) Run(ctx context.Context, req dockerdrv.RunRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockDriverMockRecorder) Run(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDriver)(nil).Run), ctx, req)
}

// RunWithOptions mocks base method.
func (m *MockDriver) RunWithOptions(ctx context.Context, opts dockerdrv.RunOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithOptions", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWithOptions indicates an expected call of RunWithOptions.
func (mr *MockDriverMockRecorder) RunWithOptions(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithOptions", reflect.TypeOf((*MockDriver)(nil).RunWithOptions), ctx, opts)
}

// Start mocks base method.
func (m *MockDriver) Start(ctx context.Context, containerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, containerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockDriverMockRecorder) Start(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDriver)(nil).Start), ctx, containerName)
}

// Stop mocks base method.
func (m *MockDriver) Stop(ctx context.Context, containerName string, gracePeriod time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, containerName, gracePeriod)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDriverMockRecorder) Stop(ctx, containerName, gracePeriod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDriver)(nil).Stop), ctx, containerName, gracePeriod)
}
